// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace BlazorOrchestrator.Web.Data.Data;

public partial class ApplicationDbContext : DbContext
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AspNetRole> AspNetRoles { get; set; }

    public virtual DbSet<AspNetRoleClaim> AspNetRoleClaims { get; set; }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

    public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }

    public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }

    public virtual DbSet<AspNetUserToken> AspNetUserTokens { get; set; }

    public virtual DbSet<Job> Jobs { get; set; }

    public virtual DbSet<JobDatum> JobData { get; set; }

    public virtual DbSet<JobGroup> JobGroups { get; set; }

    public virtual DbSet<JobInstance> JobInstances { get; set; }

    public virtual DbSet<JobJobGroup> JobJobGroups { get; set; }

    public virtual DbSet<JobOrganization> JobOrganizations { get; set; }

    public virtual DbSet<JobOrganizationsAspNetUser> JobOrganizationsAspNetUsers { get; set; }

    public virtual DbSet<JobQueue> JobQueues { get; set; }

    public virtual DbSet<JobSchedule> JobSchedules { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AspNetRole>(entity =>
        {
            entity.Property(e => e.Name).HasMaxLength(256);
            entity.Property(e => e.NormalizedName).HasMaxLength(256);
        });

        modelBuilder.Entity<AspNetRoleClaim>(entity =>
        {
            entity.HasIndex(e => e.RoleId, "IX_AspNetRoleClaims_RoleId");

            entity.Property(e => e.RoleId).IsRequired();

            entity.HasOne(d => d.Role).WithMany(p => p.AspNetRoleClaims).HasForeignKey(d => d.RoleId);
        });

        modelBuilder.Entity<AspNetUser>(entity =>
        {
            entity.HasIndex(e => e.NormalizedEmail, "EmailIndex");

            entity.Property(e => e.Email).HasMaxLength(256);
            entity.Property(e => e.NormalizedEmail).HasMaxLength(256);
            entity.Property(e => e.NormalizedUserName).HasMaxLength(256);
            entity.Property(e => e.UserName).HasMaxLength(256);

            entity.HasMany(d => d.Roles).WithMany(p => p.Users)
                .UsingEntity<Dictionary<string, object>>(
                    "AspNetUserRole",
                    r => r.HasOne<AspNetRole>().WithMany().HasForeignKey("RoleId"),
                    l => l.HasOne<AspNetUser>().WithMany().HasForeignKey("UserId"),
                    j =>
                    {
                        j.HasKey("UserId", "RoleId");
                        j.ToTable("AspNetUserRoles");
                        j.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");
                    });
        });

        modelBuilder.Entity<AspNetUserClaim>(entity =>
        {
            entity.HasIndex(e => e.UserId, "IX_AspNetUserClaims_UserId");

            entity.Property(e => e.UserId).IsRequired();

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserClaims).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<AspNetUserLogin>(entity =>
        {
            entity.HasKey(e => new { e.LoginProvider, e.ProviderKey });

            entity.HasIndex(e => e.UserId, "IX_AspNetUserLogins_UserId");

            entity.Property(e => e.LoginProvider).HasMaxLength(128);
            entity.Property(e => e.ProviderKey).HasMaxLength(128);
            entity.Property(e => e.UserId).IsRequired();

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserLogins).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<AspNetUserToken>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.LoginProvider, e.Name });

            entity.Property(e => e.LoginProvider).HasMaxLength(128);
            entity.Property(e => e.Name).HasMaxLength(128);

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserTokens).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<Job>(entity =>
        {
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.JobCodeFile)
                .IsRequired()
                .HasMaxLength(1000);
            entity.Property(e => e.JobEnvironment)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.JobName)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.UpdatedBy).HasMaxLength(500);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            entity.Property(e => e.WebhookGuid)
                .HasMaxLength(500)
                .HasColumnName("WebhookGUID");

            entity.HasOne(d => d.JobOrganization).WithMany(p => p.Jobs)
                .HasForeignKey(d => d.JobOrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Jobs_JobOrganizations");

            entity.HasOne(d => d.JobQueueNavigation).WithMany(p => p.Jobs)
                .HasForeignKey(d => d.JobQueue)
                .HasConstraintName("FK_Jobs_JobQueue");
        });

        modelBuilder.Entity<JobDatum>(entity =>
        {
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.JobDateValue).HasColumnType("datetime");
            entity.Property(e => e.JobFieldDescription)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.JobStringValue).HasMaxLength(4000);
            entity.Property(e => e.UpdatedBy).HasMaxLength(500);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Job).WithMany(p => p.JobData)
                .HasForeignKey(d => d.JobId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_JobData_Jobs");
        });

        modelBuilder.Entity<JobGroup>(entity =>
        {
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.JobGroupName)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.UpdatedBy).HasMaxLength(500);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<JobInstance>(entity =>
        {
            entity.ToTable("JobInstance");

            entity.Property(e => e.AgentId).HasMaxLength(500);
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy).HasMaxLength(500);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.JobSchedule).WithMany(p => p.JobInstances)
                .HasForeignKey(d => d.JobScheduleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_JobInstance_JobSchedule");
        });

        modelBuilder.Entity<JobJobGroup>(entity =>
        {
            entity.ToTable("Job_JobGroup");

            entity.HasOne(d => d.JobGroup).WithMany(p => p.JobJobGroups)
                .HasForeignKey(d => d.JobGroupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Job_JobGroup_JobGroups");

            entity.HasOne(d => d.Job).WithMany(p => p.JobJobGroups)
                .HasForeignKey(d => d.JobId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Job_JobGroup_Jobs");
        });

        modelBuilder.Entity<JobOrganization>(entity =>
        {
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.OrganizationName)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.UpdatedBy).HasMaxLength(500);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<JobOrganizationsAspNetUser>(entity =>
        {
            entity.ToTable("JobOrganizations_AspNetUsers");

            entity.Property(e => e.AspNetUsersId)
                .IsRequired()
                .HasMaxLength(450);
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UpdatedBy).HasMaxLength(500);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.AspNetUsers).WithMany(p => p.JobOrganizationsAspNetUsers)
                .HasForeignKey(d => d.AspNetUsersId)
                .HasConstraintName("FK_JobOrganizations_AspNetUsers_AspNetUsers");

            entity.HasOne(d => d.Organization).WithMany(p => p.JobOrganizationsAspNetUsers)
                .HasForeignKey(d => d.OrganizationId)
                .HasConstraintName("FK_JobOrganizations_AspNetUsers_JobOrganizations");
        });

        modelBuilder.Entity<JobQueue>(entity =>
        {
            entity.ToTable("JobQueue");

            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.QueueName)
                .IsRequired()
                .HasMaxLength(250);
        });

        modelBuilder.Entity<JobSchedule>(entity =>
        {
            entity.ToTable("JobSchedule");

            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.LastRun).HasColumnType("datetime");
            entity.Property(e => e.ScheduleName)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.UpdatedBy).HasMaxLength(500);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Job).WithMany(p => p.JobSchedules)
                .HasForeignKey(d => d.JobId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_JobSchedule_Jobs");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}