// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorOrchestrator.Web.Data.Data;

public partial class Job
{
    public int Id { get; set; }

    public int JobOrganizationId { get; set; }

    public string JobName { get; set; }

    public string JobEnvironment { get; set; }

    public bool JobEnabled { get; set; }

    public bool JobQueued { get; set; }

    public bool JobInProcess { get; set; }

    public bool JobInError { get; set; }

    public string JobCodeFile { get; set; }

    public string WebhookGuid { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public virtual ICollection<JobDatum> JobData { get; set; } = new List<JobDatum>();

    public virtual ICollection<JobJobGroup> JobJobGroups { get; set; } = new List<JobJobGroup>();

    public virtual JobOrganization JobOrganization { get; set; }

    public virtual ICollection<JobSchedule> JobSchedules { get; set; } = new List<JobSchedule>();
}