// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorOrchestrator.Web.Data.Data;

public partial class JobQueue
{
    public int Id { get; set; }

    public string QueueName { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public virtual ICollection<Job> Jobs { get; set; } = new List<Job>();
}