// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorDataOrchestrator.Core.Data;

public partial class JobDatum
{
    public int Id { get; set; }

    public int JobId { get; set; }

    public string JobFieldDescription { get; set; }

    public int? JobIntValue { get; set; }

    public string JobStringValue { get; set; }

    public DateTime? JobDateValue { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public virtual Job Job { get; set; }
}