// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorDataOrchestrator.Core.Data;

public partial class JobGroup
{
    public int Id { get; set; }

    public string JobGroupName { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public virtual ICollection<JobJobGroup> JobJobGroups { get; set; } = new List<JobJobGroup>();
}