// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorOrchestrator.Web.Data.Data;

public partial class JobJobGroup
{
    public int Id { get; set; }

    public int JobId { get; set; }

    public int JobGroupId { get; set; }

    public virtual Job Job { get; set; }

    public virtual JobGroup JobGroup { get; set; }
}