// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorDataOrchestrator.Core.Data;

public partial class JobOrganization
{
    public int Id { get; set; }

    public string OrganizationName { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public virtual ICollection<JobOrganizationsAspNetUser> JobOrganizationsAspNetUsers { get; set; } = new List<JobOrganizationsAspNetUser>();

    public virtual ICollection<Job> Jobs { get; set; } = new List<Job>();
}