// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorOrchestrator.Web.Data.Data;

public partial class JobSchedule
{
    public int Id { get; set; }

    public int JobId { get; set; }

    public string ScheduleName { get; set; }

    public bool Enabled { get; set; }

    public bool InProcess { get; set; }

    public bool HadError { get; set; }

    public DateTime? LastRun { get; set; }

    public int? RunEveryHour { get; set; }

    public int? StartTime { get; set; }

    public int? StopTime { get; set; }

    public bool Monday { get; set; }

    public bool Tuesday { get; set; }

    public bool Wednesday { get; set; }

    public bool Thursday { get; set; }

    public bool Friday { get; set; }

    public bool Saturday { get; set; }

    public bool Sunday { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public virtual Job Job { get; set; }

    public virtual ICollection<JobInstance> JobInstances { get; set; } = new List<JobInstance>();
}