// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorOrchestrator.Web.Data.Data;

public partial class JobOrganizationsAspNetUser
{
    public int Id { get; set; }

    public int OrganizationId { get; set; }

    public string AspNetUsersId { get; set; }

    public string RoleName { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public virtual AspNetUser AspNetUsers { get; set; }

    public virtual JobOrganization Organization { get; set; }
}